name: rop
description: >
  ROP is a library designed to handle errors in a structured and 
  fluent way using the Result<T> structure. Inspired by functional 
  programming principles, it enables clear workflows that separate 
  success and error paths.

version: 1.0.0
repository: https://github.com/odmaroliv/rop

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
